[target.riscv32imc-unknown-none-elf]
runner = "espflash flash --monitor"

rustflags = [
    "-C", "link-arg=-Tlinkall.x",
]

[target.riscv32imac-unknown-none-elf]
runner = "espflash flash --monitor"

rustflags = [
    "-C", "link-arg=-Tlinkall.x",
]

[target.xtensa-esp32-none-elf]
runner = "espflash flash --monitor"

rustflags = [
    "-C", "link-arg=-Tlinkall.x",
]

[target.xtensa-esp32s2-none-elf]
runner = "espflash flash --monitor"

rustflags = [
    "-C", "link-arg=-Tlinkall.x",
]

[target.xtensa-esp32s3-none-elf]
runner = "espflash flash --monitor"

rustflags = [
    "-C", "link-arg=-Tlinkall.x",
]

[build]
target = "riscv32imc-unknown-none-elf"
 
[unstable]
build-std = [ "core", "alloc" ]
